# Generated by Django 3.2 on 2021-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
            ],
        ),
    ]
