# Generated by Django 3.2 on 2021-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='fabricante',
            field=models.CharField(help_text='Fabricante', max_length=200),
        ),
    ]
