# Generated by Django 3.2 on 2021-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210531_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('typeMain', models.CharField(blank=True, choices=[('p', 'Percurso'), ('h', 'Horímetro'), ('d', 'Dia'), ('c', 'Ciclo')], default='d', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Manutenção',
                'ordering': ['name', 'typeMain', 'value'],
            },
        ),
    ]
