# Generated by Django 3.2 on 2021-06-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_maintenancetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planDate', models.DateTimeField()),
                ('executedDate', models.DateTimeField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'Planejado'), ('e', 'Executado'), ('a', 'Atrasado')], default='p', max_length=1)),
                ('employeer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employeer')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.equipment')),
            ],
            options={
                'verbose_name_plural': 'Order de Serviço',
                'ordering': ['equipment', 'planDate', 'executedDate', 'status'],
            },
        ),
    ]
