# Generated by Django 3.2 on 2021-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210601_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='executedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='planDate',
            field=models.DateTimeField(),
        ),
    ]
