# Generated by Django 3.2 on 2021-06-01 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210601_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='planDate',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 20, 31, 33, 584718, tzinfo=utc)),
        ),
    ]
